[build]
  publish = "."
  base = "sites/luxecodes"

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "default-src 'self'; connect-src 'self' https://couponcanon.com https://www.couponcanon.com; script-src 'self' 'unsafe-inline' blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https:; object-src 'none'; base-uri 'self'; frame-ancestors 'none';"

[[headers]]
  for = "/"
  [headers.values]
  Cache-Control = "public, max-age=3600"
