[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/brand"
  to = "/.netlify/functions/brand"
  status = 200

[[redirects]]
  from = "/api/brands"
  to = "/.netlify/functions/brands"
  status = 200

[[redirects]]
  from = "/api/codes"
  to = "/.netlify/functions/codes"
  status = 200

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200
